### PR TITLE
refactor catch2 dep to use find_package. fix for #9

### PR DESCRIPTION
**Pull request by steakhal**

### CODE REVIEW

**Comment by steakhal** [comment]
It will probably work if we use Conan for managing dependencies, which would create the necessary FindCatch2.cmake in the build directory. That would make the `find_package(Catch2 REQUIRED)` succeed.

**Comment by steakhal** [comment]
Don't merge it yet.

**Comment by Neargye** [comment]
Maybe add
```
find_package(Catch2)
if (NOT ${Catch2_FOUND})
    if (NOT EXISTS ${CMAKE_SOURCE_DIR}/test/catch2)
        make_directory(${CMAKE_SOURCE_DIR}/test/catch2)
    endif()
    if (NOT EXISTS ${CMAKE_SOURCE_DIR}/test/catch2/catch.hpp)
        file(
        DOWNLOAD
            https://github.com/catchorg/Catch2/releases/download/v2.9.1/catch.hpp ${CMAKE_SOURCE_DIR}/test/catch2/catch.hpp
        STATUS
            status
        LOG
            log
        )
        list(GET status 0 status_code)
        list(GET status 1 status_string)
        if(NOT status_code EQUAL 0)
            message(FATAL_ERROR "error downloading Catch2 lib: ${status_string}" "${log}")
        endif()
endif()
```

**Comment by steakhal** [comment]
I don't think that we should provide an alternative method for getting the catch header.

I think downloading and installing catch would be the user's responsibility.
If that is already installed, then that will be found.
If not installed, but consumes as a conan package, it will be all right, handled correctly.

The only problem is that now the build bot does not have knowledge about catch.
I think that should we fix.

**Comment by Neargye** [comment]
Well, then I will correct the CI scripts. Need some time for test.

**Comment by steakhal** [comment]
Nonono, I will do everything. Just enjoy your vacation ;)

Prepare for PR :D

**Comment by Neargye** [comment]
To install catch2 we can use conan
https://docs.conan.io/en/latest/integrations/ci/appveyor.html
https://docs.conan.io/en/latest/integrations/ci/travisci.html

**Comment by Neargye** [comment]
Or install via cmake, yep

**Comment by steakhal** [comment]
We can, but I want to migrate to conan in a different PR.
For now, I will fix this.

Using conan for this has also some other benefits, like drop-in ready build images (conanio docker images), etc. So definitely tempting.

**Comment by Neargye** [comment]
I sent an invite, in case I am not available for communication.

**Comment by steakhal** [comment]
Thank you for your invite.

I cannot tell you how much I hate to mess with CI related stuff xD
Its a bad day :D

**Comment by steakhal** [comment]
huh, seems working now :D

If you think its ok for you, accept it.

**Comment by Neargye** [comment]
Thanks!

**Pull request merged**
